language: python
matrix:
  include:
    - python: "2.7"
      env: TEST_SUITE=suite_2_7
    - python: "3.3"
      env: TEST_SUITE=suite_3_3

branches:
  only:
    - dev

script: python BenchmarkDB/main.py --debug

virtualenv:
    system_site_packages: true

before_install:
  - SITE_PKG_DIR=$VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/site-packages
  - rm -f $VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/no-global-site-packages.txt
  - apt-get install python-numpy
  - apt-get install python-scipy