# tasks for installing Postgres-XL

- name: Install Git
  yum:
  - name: git
  - state: present

- name: Clone Git Repo
  git:
  - repo: {{ git_url }}
  - dest: {{ git_dest }}

- name: Yum install dependencies
  yum: pkg={{ item }} state=present
  with_items:
  - @Development tools
  - readline-devel
  - zlib-devel

- name: Configure postgres-xl
  command: ./configure
  args:
  - chdir: {{ git_dest }}

- name: Make postgres-xl
  command: gmake
  args:
  - chdir: {{ git_dest }}

- name: Install postgres-xl
  command: ./configure
  args:
  - chdir: {{ git_dest }}

- name: Add the postgres user
  user: name={{ db_user }}



























#- name: test
#  user: name="foo" state="present"
#
#- name: testtt
#  command: echo fooooooo
#  sudo_user: foo