---
# This playbook  deploys the mongodb configuration servers

- name: Create data directory for mongoc configuration server
  file:
    path: "{{ mongodb_datadir_prefix }}/configdb"
    state: directory
    owner: mongod
    group: mongod

- name: Copy the keyfile for authentication
  copy: src=roles/mongod/files/secret dest={{ mongodb_datadir_prefix }}/secret owner=mongod group=mongod mode=0400

- name: Create the directory for the Config DB
  file:
    path: /data/configdb
    state: directory
    recurse: yes

- name: Start the mongo configuration server service
  shell: mongod --fork --logpath /var/log/mongo-configdb.log --configsvr --port {{ mongoc_port }}

- name: Pause for a moment
  pause: seconds=5
