---
# This role deploys the mongod processes
#
- name: create data directory for mongodb
  file: path={{ mongodb_datadir_prefix }} state=directory owner=mongod group=mongod

- name: Copy the keyfile for authentication
  copy: src=secret dest={{ mongodb_datadir_prefix }}secret owner=mongod group=mongod mode=0400

- name: If mongod is already running, stop it!
  service: name=mongod state=stopped

#- name: Start mongo
#  service: name=mongod state=started

- name: Start the mongodb service
  command: mongod --fork --logpath /var/log/mongodb.log --replSet rs0 --journal --smallfiles --bind_ip {{ inventory_hostname }}
  ignore_errors: yes

- name: Pause for a while
  pause: seconds=5
